config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/' => 'tops#top',as: 'top_path'
  get '/about' => 'tops#about'
  get 'calender' => 'calenders#calender',as:"calender_path"
  
  resources :incomes
  resources :payment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
	def calender
		
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def delete
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def delete
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    calender_path
  end

  def after_sign_out_path_for(resource)
    top_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callenders_helper.rb
module CallendersHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/calenders/calender.html.erb
calender

app/views/incomes/create.html.erb
<h1>Incomes#create</h1>
<p>Find me in app/views/incomes/create.html.erb</p>

app/views/incomes/delete.html.erb
<h1>Incomes#delete</h1>
<p>Find me in app/views/incomes/delete.html.erb</p>

app/views/incomes/edit.html.erb
<h1>Incomes#edit</h1>
<p>Find me in app/views/incomes/edit.html.erb</p>

app/views/incomes/index.html.erb
<h1>Incomes#index</h1>
<p>Find me in app/views/incomes/index.html.erb</p>

app/views/incomes/new.html.erb
<h1>Incomes#new</h1>
<p>Find me in app/views/incomes/new.html.erb</p>

app/views/incomes/show.html.erb
<h1>Incomes#show</h1>
<p>Find me in app/views/incomes/show.html.erb</p>

app/views/incomes/update.html.erb
<h1>Incomes#update</h1>
<p>Find me in app/views/incomes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <nav class="navbar">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample5">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <p class="navbar-brand">家計簿</p>
            </div>
            <div class="collapse navbar-collapse" id="navbarEexample5">
              <% if user_signed_in? %>
                <ul class="nav navbar-nav">
                  <li><%= link_to "HOME", top_path_url %></li>
                  <li><%= link_to "家計簿について", about_path %></li>
                  <li><%= link_to "マイページ"  %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
              <% else %>
                <ul class="nav navbar-nav">
                  <li><%= link_to "HOME", top_path_url %></li>
                  <li><%= link_to "家計簿について", about_path %></li>
                  <li><%= link_to "新規登録", new_user_registration_path %></li>
                  <li><%= link_to "ログイン", new_user_session_path %></li>
                </ul>
              <% end %>
              <p class="navbar-text">ようこそ ゲスト さん。</p>
            </div>
          </div>
        </nav>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/delete.html.erb
<h1>Payments#delete</h1>
<p>Find me in app/views/payments/delete.html.erb</p>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/payments/update.html.erb
<h1>Payments#update</h1>
<p>Find me in app/views/payments/update.html.erb</p>

app/views/tops/about.html.erb
<h1>Tops#about</h1>
<p>Find me in app/views/tops/about.html.erb</p>

app/views/tops/top.html.erb
<h1>家計簿</h1>